"""Five synthetic claims (copied from Section 26 / 27 of PMG.ipynb)."""

DEMO_CLAIMS = [
 {"ClaimID": "CLM-0001",
  "BookingType": "Flight", "BookingChannel": "PTS Web", "ClaimSubmissionChannel": "Web",
  "BookingAmount": 820.0, "BetterRateAmount": 690.0, "ClaimAmount": 130.0, "ClaimPoints": 0,
  "BookingDate": "2025-01-10", "TravelStartDate": "2025-05-02", "TravelEndDate": "2025-05-09",
  "ClaimSubmissionDate": "2025-02-15 10:30", "LoyaltyMemberSinceDate": "2019-06-01",
  "LoyaltyTier": "Gold", "AccountStatus": "Active", "CustomerLifetimeValue": 4200.0,
  "PriorClaimsCount": 5, "PriorApprovedClaimsCount": 5,
  "ProofType": "PDF Quote", "ProofQualityFlag": "Verified", "AttachmentCount": 4,
  "RestrictionsMatchFlag": True, "BlackoutDateOrExcludedFare": False, "IsMultiSegmentBooking": False,
  "BetterRateURL": "https://competitor.example/deal/123", "BetterRateVendorName": "Expedia",
  "FareOrRatePlanFlexibility": "Refundable", "BookingSpecialConsiderations": None,
  "NumberOfPassengers": 2, "IsFamilyBooking": True, "AdvisorTenureMonths": 40,
  "CustomerComments": "Found the exact same refundable flight cheaper on Expedia, PDF attached."},

 {"ClaimID": "CLM-0002",
  "BookingType": "Hotel/Lodging", "BookingChannel": "App", "ClaimSubmissionChannel": "Mobile App",
  "BookingAmount": 540.0, "BetterRateAmount": 531.0, "ClaimAmount": 9.0, "ClaimPoints": 0,
  "BookingDate": "2025-03-01", "TravelStartDate": "2025-06-20", "TravelEndDate": "2025-06-25",
  "ClaimSubmissionDate": "2025-07-02 22:05", "LoyaltyMemberSinceDate": "2024-06-15",
  "LoyaltyTier": "Standard", "AccountStatus": "Suspended", "CustomerLifetimeValue": 280.0,
  "PriorClaimsCount": 3, "PriorApprovedClaimsCount": 0,
  "ProofType": None, "ProofQualityFlag": "Insufficient", "AttachmentCount": 0,
  "RestrictionsMatchFlag": False, "BlackoutDateOrExcludedFare": False, "IsMultiSegmentBooking": False,
  "BetterRateURL": None, "BetterRateVendorName": "Booking.com",
  "FareOrRatePlanFlexibility": "Non-Refundable", "BookingSpecialConsiderations": None,
  "NumberOfPassengers": 1, "IsFamilyBooking": False, "AdvisorTenureMonths": 6,
  "CustomerComments": "Pretty sure it was cheaper, no screenshot though."},

 {"ClaimID": "CLM-0003",
  "BookingType": "Cruise", "BookingChannel": "PTS Web", "ClaimSubmissionChannel": "Email",
  "BookingAmount": 2600.0, "BetterRateAmount": 780.0, "ClaimAmount": 1820.0, "ClaimPoints": 5000,
  "BookingDate": "2024-11-01", "TravelStartDate": "2025-02-01", "TravelEndDate": "2025-02-10",
  "ClaimSubmissionDate": "2025-02-25 09:00", "LoyaltyMemberSinceDate": "2020-03-03",
  "LoyaltyTier": "Silver", "AccountStatus": "Active", "CustomerLifetimeValue": 1600.0,
  "PriorClaimsCount": 4, "PriorApprovedClaimsCount": 1,
  "ProofType": "Screenshot", "ProofQualityFlag": "Ambiguous", "AttachmentCount": 1,
  "RestrictionsMatchFlag": False, "BlackoutDateOrExcludedFare": True, "IsMultiSegmentBooking": False,
  "BetterRateURL": "https://competitor.example/cruise/9", "BetterRateVendorName": "Vendor Direct",
  "FareOrRatePlanFlexibility": "Change Fee Applies", "BookingSpecialConsiderations": "Honeymoon package",
  "NumberOfPassengers": 2, "IsFamilyBooking": False, "AdvisorTenureMonths": 52,
  "CustomerComments": "Found it way cheaper on another site, refund the difference please."},

 {"ClaimID": "CLM-0004",
  "BookingType": "Package", "BookingChannel": "App", "ClaimSubmissionChannel": "Web",
  "BookingAmount": 1250.0, "BetterRateAmount": 1090.0, "ClaimAmount": 160.0, "ClaimPoints": 0,
  "BookingDate": "2025-04-01", "TravelStartDate": "2025-08-12", "TravelEndDate": "2025-08-20",
  "ClaimSubmissionDate": "2025-05-20 16:45", "LoyaltyMemberSinceDate": "2021-11-11",
  "LoyaltyTier": "Silver", "AccountStatus": "Active", "CustomerLifetimeValue": 2100.0,
  "PriorClaimsCount": 2, "PriorApprovedClaimsCount": 1,
  "ProofType": "Confirmation Email", "ProofQualityFlag": "Verified", "AttachmentCount": 2,
  "RestrictionsMatchFlag": True, "BlackoutDateOrExcludedFare": False, "IsMultiSegmentBooking": True,
  "BetterRateURL": "https://competitor.example/pkg/55", "BetterRateVendorName": "Travelocity",
  "FareOrRatePlanFlexibility": "Partially Flexible", "BookingSpecialConsiderations": "Group booking",
  "NumberOfPassengers": 4, "IsFamilyBooking": True, "AdvisorTenureMonths": 30,
  "CustomerComments": "Same package same dates, cheaper total on Travelocity, screenshot attached."},

 {"ClaimID": "CLM-0005",
  "BookingType": "Car", "BookingChannel": "Agent-Assisted", "ClaimSubmissionChannel": "Call Center",
  "BookingAmount": 600.0, "BetterRateAmount": 588.0, "ClaimAmount": 12.0, "ClaimPoints": 0,
  "BookingDate": "2025-02-20", "TravelStartDate": "2025-04-15", "TravelEndDate": "2025-04-19",
  "ClaimSubmissionDate": "2025-03-05 14:00", "LoyaltyMemberSinceDate": "2019-09-09",
  "LoyaltyTier": "Gold", "AccountStatus": "Active", "CustomerLifetimeValue": 3800.0,
  "PriorClaimsCount": 6, "PriorApprovedClaimsCount": 5,
  "ProofType": "PDF Quote", "ProofQualityFlag": "Verified", "AttachmentCount": 3,
  "RestrictionsMatchFlag": True, "BlackoutDateOrExcludedFare": False, "IsMultiSegmentBooking": False,
  "BetterRateURL": "https://competitor.example/car/77", "BetterRateVendorName": "Priceline",
  "FareOrRatePlanFlexibility": "Refundable", "BookingSpecialConsiderations": "Corporate rate",
  "NumberOfPassengers": 1, "IsFamilyBooking": False, "AdvisorTenureMonths": 25,
  "CustomerComments": "Only a couple dollars cheaper elsewhere but I still want the match."},
]
