// ClaimForm.jsx - the claim intake form. Design goals: nothing is typed when it can be chosen.
//  * categories are chips / dropdowns whose values come from the backend (/api/claims/options)
//  * yes/no questions are two-button toggles in plain language
//  * refund amount, filing time, channel, account tier and history are computed by the SERVER, not asked
//  * the Claim ID is generated by the backend when the form opens and shown read-only
import { useEffect, useMemo, useRef, useState } from 'react';
import { api } from '../api.js';
import { log } from '../logger.js';

const today = () => new Date().toISOString().slice(0, 10);
const money = (n) => (Number.isFinite(n) ? n.toLocaleString('en-US', { style: 'currency', currency: 'USD' }) : '—');

// ---- small reusable controls ---------------------------------------------------------------
// Field wrapper: label + control + inline error + optional hint.
const Field = ({ label, error, hint, children }) => (
  <div className={`field ${error ? 'has-error' : ''}`}>
    <label>{label}</label>
    {children}
    {hint && !error && <small className="muted">{hint}</small>}
    {error && <small className="err">{error}</small>}
  </div>
);
// Row of clickable chips for picking ONE option from a short list.
const Chips = ({ value, onChange, options }) => (
  <div className="chips" role="radiogroup">
    {options.map((o) => {
      const v = o.value ?? o; const l = o.label ?? o;
      return <button type="button" key={v} role="radio" aria-checked={value === v} className={`chip ${value === v ? 'on' : ''}`} onClick={() => onChange(v)}>{l}</button>;
    })}
  </div>
);
// Yes / No segmented toggle bound to a boolean.
const YesNo = ({ value, onChange }) => (
  <div className="seg" role="radiogroup">
    <button type="button" role="radio" aria-checked={value === true} className={value === true ? 'on' : ''} onClick={() => onChange(true)}>Yes</button>
    <button type="button" role="radio" aria-checked={value === false} className={value === false ? 'on' : ''} onClick={() => onChange(false)}>No</button>
  </div>
);
const Select = ({ value, onChange, options, placeholder }) => (
  <select value={value} onChange={(e) => onChange(e.target.value)}>
    {placeholder && <option value="">{placeholder}</option>}
    {options.map((o) => <option key={o.value ?? o} value={o.value ?? o}>{o.label ?? o}</option>)}
  </select>
);
const Money = ({ value, onChange, placeholder }) => (
  <div className="money"><span>$</span>
    <input inputMode="decimal" value={value} placeholder={placeholder}
      onChange={(e) => /^\d{0,6}(\.\d{0,2})?$/.test(e.target.value) && onChange(e.target.value)} /> {/* only digits + 2 decimals can be typed */}
  </div>
);

// ---- initial answers ---------------------------------------------------------------------------
const EMPTY = {
  bookingType: '', bookingChannel: '', bookingAmount: '', bookingDate: '', travelStartDate: '', travelEndDate: '',
  passengers: 1, flexibility: '', specialConsiderations: 'None', familyBooking: false, multiSegment: false, advisorTenure: 'unknown',
  vendorName: '', betterRateAmount: '', betterRateUrl: '', restrictionsMatch: null, blackoutOrExcluded: null,
  proofType: '', proofClarity: '', pointsRequested: '', comments: '',
};

export default function ClaimForm({ onDone, onSessionExpired }) {
  const [opts, setOpts] = useState(null); // dropdown values from the backend
  const [claimId, setClaimId] = useState(''); // dynamic claim id
  const [f, setF] = useState(EMPTY); // all answers
  const [files, setFiles] = useState([]); // proof files
  const [errors, setErrors] = useState({}); // field -> message
  const [banner, setBanner] = useState(''); // form-level error
  const [busy, setBusy] = useState(false);
  const started = useRef(false); // StrictMode runs effects twice in dev; this keeps us to ONE claim id

  // Clears a field's error as soon as the customer changes it, so stale red messages never linger.
  const clearErr = (...ks) => setErrors((p) => Object.fromEntries(Object.entries(p).filter(([k]) => !ks.includes(k))));
  const set = (k) => (v) => { setF((p) => ({ ...p, [k]: v })); clearErr(k); }; // setter factory: set('bookingType')(value)

  // On mount: load dropdown options and request a fresh claim id.
  useEffect(() => {
    if (started.current) return;
    started.current = true;
    Promise.all([api.options(), api.newClaimId()])
      .then(([o, c]) => { log.setTrace(c.claimId); log.summary(`claim form opened, claim ID ${c.claimId}`); log.debug('dropdown options loaded', Object.keys(o)); setOpts(o); setClaimId(c.claimId); })
      .catch((e) => (e.status === 401 ? onSessionExpired() : setBanner(e.message)));
  }, [onSessionExpired]);

  // Refund = what they paid minus the cheaper price; computed live so the customer sees what they would claim.
  const refund = useMemo(() => Number(f.bookingAmount) - Number(f.betterRateAmount), [f.bookingAmount, f.betterRateAmount]);
  const pct = useMemo(() => (refund / Number(f.bookingAmount)) * 100, [refund, f.bookingAmount]);

  // Client-side validation mirrors the server rules so mistakes are caught before the round trip.
  const validate = () => {
    const e = {}; const need = 'Please choose one';
    if (!f.bookingType) e.bookingType = need;
    if (!f.bookingChannel) e.bookingChannel = need;
    if (!(Number(f.bookingAmount) > 0)) e.bookingAmount = 'Enter the amount you paid';
    if (!f.bookingDate) e.bookingDate = 'Pick a date'; else if (f.bookingDate > today()) e.bookingDate = 'Cannot be in the future';
    if (!f.travelStartDate) e.travelStartDate = 'Pick a date'; else if (f.bookingDate && f.travelStartDate < f.bookingDate) e.travelStartDate = 'Cannot be before the booking date';
    if (!f.travelEndDate) e.travelEndDate = 'Pick a date'; else if (f.travelStartDate && f.travelEndDate < f.travelStartDate) e.travelEndDate = 'Cannot be before travel start';
    if (!f.flexibility) e.flexibility = need;
    if (!f.vendorName) e.vendorName = 'Which site had the better rate?';
    if (!(Number(f.betterRateAmount) > 0)) e.betterRateAmount = 'Enter the lower price';
    else if (Number(f.betterRateAmount) >= Number(f.bookingAmount)) e.betterRateAmount = 'Must be lower than what you paid';
    if (f.betterRateUrl && !/^https?:\/\/\S+\.\S+/i.test(f.betterRateUrl)) e.betterRateUrl = 'Paste the full link, starting with https://';
    if (f.restrictionsMatch === null) e.restrictionsMatch = need;
    if (f.blackoutOrExcluded === null) e.blackoutOrExcluded = need;
    const anyProof = f.proofType || f.proofClarity || files.length;
    if (anyProof && !(f.proofType && f.proofClarity && files.length)) e.proofFiles = 'Choose the proof type, how clear it is, and attach a file — or clear all three';
    return e;
  };

  // File picker: accept only PDF/PNG/JPG, max 5 files of 5 MB, and tell the user why anything was skipped.
  const addFiles = (list) => {
    const ok = []; const skipped = [];
    [...list].forEach((x) => (['application/pdf', 'image/png', 'image/jpeg'].includes(x.type) && x.size <= 5 * 1024 * 1024 ? ok : skipped).push(x));
    const merged = [...files, ...ok].slice(0, 5);
    setFiles(merged);
    setErrors((p) => ({ ...p, proofFiles: skipped.length ? `${skipped.length} file(s) skipped — use PDF, PNG or JPG up to 5 MB` : (merged.length < files.length + ok.length ? 'Maximum 5 files' : undefined) }));
  };

  const submit = async (ev) => {
    ev.preventDefault();
    setBanner('');
    const e = validate();
    setErrors(e);
    if (Object.keys(e).length) { log.info('client-side validation failed; not sent', e); document.querySelector('.has-error')?.scrollIntoView({ behavior: 'smooth', block: 'center' }); return; }
    setBusy(true);
    try {
      // The SAME claimId generated at the top goes to the backend, then to the model, then back in the result.
      log.info('submit pressed: sending claim to BACKEND');
      const result = await api.submitClaim({ ...f, claimId, pointsRequested: Number(f.pointsRequested || 0) }, files);
      log.summary(`claim ${result.claimId} result: ${result.decision} (P=${result.probabilityApproved})`, result);
      onDone(result);
    } catch (err) {
      if (err.status === 401) return onSessionExpired();
      log.error(`submit failed: ${err.message} (HTTP ${err.status})`, err.fields);
      setBanner(err.message);
      if (err.fields) setErrors(err.fields); // show server-side messages next to the right fields
    } finally { setBusy(false); }
  };

  if (!opts) return <div className="center muted">{banner || 'Preparing your claim…'}</div>;

  return (
    <form onSubmit={submit} noValidate>
      <div className="claim-head">
        <div><h1>File a price match claim</h1><p className="muted">Takes about 2 minutes. Fields marked ✓ are filled in for you.</p></div>
        <div className="claimid"><small>Claim ID</small><b>{claimId}</b></div>
      </div>

      {/* ---------- 1. the booking ---------- */}
      <section className="card">
        <h2><span className="n">1</span> Your booking with us</h2>
        <Field label="What did you book?" error={errors.bookingType}><Chips value={f.bookingType} onChange={set('bookingType')} options={opts.BOOKING_TYPES} /></Field>
        <Field label="How did you book it?" error={errors.bookingChannel}><Chips value={f.bookingChannel} onChange={set('bookingChannel')} options={opts.BOOKING_CHANNELS} /></Field>
        {f.bookingChannel === 'Agent-Assisted' && (
          <Field label="How long has your advisor worked with us?" hint="Best guess is fine">
            <Select value={f.advisorTenure} onChange={set('advisorTenure')} options={opts.ADVISOR_TENURE} />
          </Field>
        )}
        <div className="grid3">
          <Field label="Total you paid" error={errors.bookingAmount}><Money value={f.bookingAmount} onChange={set('bookingAmount')} placeholder="820.00" /></Field>
          <Field label="Booking date" error={errors.bookingDate}><input type="date" max={today()} value={f.bookingDate} onChange={(e) => set('bookingDate')(e.target.value)} /></Field>
          <Field label="Travelers" hint="Including you">
            <div className="stepper"><button type="button" onClick={() => set('passengers')(Math.max(1, f.passengers - 1))}>−</button><b>{f.passengers}</b><button type="button" onClick={() => set('passengers')(Math.min(20, f.passengers + 1))}>+</button></div>
          </Field>
          <Field label="Travel starts" error={errors.travelStartDate}><input type="date" min={f.bookingDate} value={f.travelStartDate}
            onChange={(e) => { setF((p) => ({ ...p, travelStartDate: e.target.value, travelEndDate: p.travelEndDate < e.target.value ? e.target.value : p.travelEndDate })); clearErr('travelStartDate', 'travelEndDate'); }} /></Field>
          <Field label="Travel ends" error={errors.travelEndDate}><input type="date" min={f.travelStartDate} value={f.travelEndDate} onChange={(e) => set('travelEndDate')(e.target.value)} /></Field>
        </div>
        <Field label="Your fare / rate type" error={errors.flexibility}><Chips value={f.flexibility} onChange={set('flexibility')} options={opts.FLEXIBILITY} /></Field>
        <div className="grid3">
          <Field label="Any special fare or discount?"><Select value={f.specialConsiderations} onChange={set('specialConsiderations')} options={opts.SPECIAL} /></Field>
          <Field label="Family booking?"><YesNo value={f.familyBooking} onChange={set('familyBooking')} /></Field>
          <Field label="Multiple flights / hotels in one booking?"><YesNo value={f.multiSegment} onChange={set('multiSegment')} /></Field>
        </div>
      </section>

      {/* ---------- 2. the better rate ---------- */}
      <section className="card">
        <h2><span className="n">2</span> The better rate you found</h2>
        <div className="grid3">
          <Field label="Where did you find it?" error={errors.vendorName}><Select value={f.vendorName} onChange={set('vendorName')} options={opts.VENDORS} placeholder="Choose a site…" /></Field>
          <Field label="Their price for the same trip" error={errors.betterRateAmount}><Money value={f.betterRateAmount} onChange={set('betterRateAmount')} placeholder="690.00" /></Field>
          <Field label="Link to the offer (optional)" error={errors.betterRateUrl}><input type="url" value={f.betterRateUrl} placeholder="https://…" onChange={(e) => set('betterRateUrl')(e.target.value)} /></Field>
        </div>
        {refund > 0 && (
          <div className="refund">✓ Refund you're requesting: <b>{money(refund)}</b> <span className="muted">({pct.toFixed(1)}% less than you paid)</span></div>
        )}
        <Field label="Is their offer for the same trip — same dates, room/cabin class and cancellation rules?" error={errors.restrictionsMatch}><YesNo value={f.restrictionsMatch} onChange={set('restrictionsMatch')} /></Field>
        <Field label="Was your booking a blackout-date or excluded fare?" error={errors.blackoutOrExcluded} hint="Shown in your fare rules / confirmation email. Choose No if you're unsure."><YesNo value={f.blackoutOrExcluded} onChange={set('blackoutOrExcluded')} /></Field>
      </section>

      {/* ---------- 3. proof ---------- */}
      <section className="card">
        <h2><span className="n">3</span> Proof <span className="muted">(strongly recommended)</span></h2>
        <Field label="What are you attaching?"><Chips value={f.proofType} onChange={(v) => { set('proofType')(f.proofType === v ? '' : v); clearErr('proofFiles'); }} options={opts.PROOF_TYPES} /></Field>
        <Field label="How clearly does it show the same trip and price?"><Select value={f.proofClarity} onChange={(v) => { set('proofClarity')(v); clearErr('proofFiles'); }} options={opts.PROOF_CLARITY} placeholder="Choose…" /></Field>
        <Field label="Files (PDF, PNG or JPG · up to 5 · 5 MB each)" error={errors.proofFiles}>
          <label className="drop">
            <input type="file" multiple accept=".pdf,.png,.jpg,.jpeg" onChange={(e) => { addFiles(e.target.files); e.target.value = ''; }} />
            <span>📎 Click to choose files</span>
          </label>
          {files.map((x, i) => (
            <div className="file" key={i}>{x.name} <small className="muted">{(x.size / 1024).toFixed(0)} KB</small>
              <button type="button" className="link" onClick={() => setFiles(files.filter((_, j) => j !== i))}>remove</button></div>
          ))}
        </Field>
        <div className="grid2">
          <Field label="Also request loyalty points? (optional)"><input inputMode="numeric" value={f.pointsRequested} placeholder="0"
            onChange={(e) => /^\d{0,7}$/.test(e.target.value) && set('pointsRequested')(e.target.value)} /></Field>
          <Field label="Anything else we should know? (optional)" hint={`${f.comments.length}/500`}>
            <textarea rows={3} maxLength={500} value={f.comments} onChange={(e) => set('comments')(e.target.value)} placeholder="e.g. Same refundable flight, cheaper on Expedia" />
          </Field>
        </div>
      </section>

      <section className="card auto">
        <h3>Filled in for you ✓</h3>
        <p className="muted">Claim ID, refund amount, filing time, filing channel (Web), and your loyalty tier, account status and claim history come from your account — you can't and don't need to enter them.</p>
      </section>

      {banner && <div className="alert" role="alert">{banner}</div>}
      <div className="submit-bar"><button className="primary big" disabled={busy}>{busy ? 'Checking your claim…' : 'Submit claim'}</button></div>
    </form>
  );
}
